---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  nodevops.io/generated-by: kustomize
  nodevops.io/kustomize-assembly: instance/works

resources:
  - ../../components/atlantis

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
  # atlantis
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: atlantis
      namespace: atlantis
    path: patches/atlantis/atlantis--deployment.yml
