---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  nodevops.io/generated-by: kustomize
  nodevops.io/kustomize-assembly: instance/ok-v3.0.x-ok-v2.1.0

resources:
  - ../../components/atlantis-no-ns-in-resources

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
  # atlantis
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: atlantis
    path: patches/atlantis/atlantis--deployment.yml
