---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlantis

commonAnnotations:
  nodevops.io/kustomize-component: atlantis

resources:
  - resources/namespace.yml
  - resources/deployment.yml

images:
  - name: FIXME/vault
    newName: vault
    newTag: 1.1.2
  - name: FIXME/consul-template
    newName: hashicorp/consul-template
    newTag: 0.20.0-alpine
  - name: FIXME/atlantis
    newName: runatlantis/atlantis
    newTag: v0.7.1
